Do not check missing libraries for libre2
The check fails with the following error:

ERROR: lib/libre2.0.0.0.dylib: missing library: @rpath/libre2.0.dylib